import React from 'react'
import Navbar from '@components/MainPage/Navbar'
import Section1 from '@components/MainPage/Section1'
import PopularComplaint from '@components/MainPage/PopularComplaint'
import Categories from '@components/MainPage/Categories'
import ComplaintStatistic from '@components/MainPage/ComplaintStatistic'
import Footer from '@components/MainPage/Footer'
const layout = () => {
    return (

        <html>
            {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" />
            <link href="https://fonts.googleapis.com/css2?family=Jersey+15&display=swap" rel="stylesheet" /> */}
            <body>
                <div>
                    <Navbar />
                    <Section1 />
                    <PopularComplaint />
                    <Categories />
                    <ComplaintStatistic />
                    <Footer />
                </div>
            </body>
        </html>
    )
}

export default layout


// import type { Metadata } from "next";
// import { IBM_Plex_Sans } from "next/font/google";
// import { cn } from "@/lib/utils";
// import "./globals.css";
// import { Toaster } from "@/components/ui/sonner";

// const IBMPlex = IBM_Plex_Sans({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
//   variable: "--font-ibm-plex",
// });

// export const metadata: Metadata = {
//   title: "Şikayət Qutusu",
//   description: "Generated by PS Studio",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={cn("font-IBMPlex antialiased", IBMPlex.variable)}>
//         {children}
//         <Toaster />
//       </body>
//     </html>
//   );
// }